languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
- "**.min.js"
- "**.min.css"
## Excluding Tests, Specs and Vendor Directories at any Level
- tests/**/*
- tests.int/**/*
- spec/**/*
- "**/vendor/**/*"
## Excluding
- "admin/sxd/**/*"
