build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=some-file tests --config tests/phpunit.xml'
                coverage:
                    file: 'some-file'
                    format: 'clover'
filter:
    excluded_paths:
        - tests/*
        - vendor/*
        - admin/sxd/*
coding_style:
    php:
        indentation:
            general:
                size: 2